export const UI_NAME = 'ui'

export const MESSAGE_GET_DATA = 'get-data'
export const MESSAGE_CHANGE_SETTINGS = 'change-settings'
export const MESSAGE_GOTO = 'goto-link'
export const MESSAGE_COPY_LINK = 'copy-link'
export const MESSAGE_GENERATE = 'generate-link'
export const MESSAGE_ADDCSS = 'add-css'

export const GENERATE_TYPE_AWESOME = 'awesome'
export const GENERATE_TYPE_REFERENCE = 'reference'
export const GENERATE_TYPE_REFERENCE_RELATIVE = 'reference_relative'

export const CONTEXT_MEUNITEM_ID_OPEN = 'open'
export const CONTEXT_MEUNITEM_ID_TRANSLATE = 'translate'
export const CONTEXT_MEUNITEM_ID_SEARCH_ZHIHU = 'search_zhihu'
export const CONTEXT_MEUNITEM_ID_SEARCH_JUEJIN = 'search_juejin'
export const CONTEXT_MEUNITEM_ID_SEARCH_WIKI = 'search_wiki'
export const CONTEXT_MEUNITEM_ID_SEARCH_GIT = 'search_git'
export const CONTEXT_MEUNITEM_ID_SEARCH_NPM = 'search_npm'
export const CONTEXT_MEUNITEM_ID_SEARCH_MDN = 'search_mdn'
export const CONTEXT_MEUNITEM_ID_READ_SOURCE = 'read_source'